# Generated by Claude Code
import csv
import subprocess
import platform
from pathlib import Path
from textwrap import dedent


_SCRIPT_DIR = Path(__file__).parent


CURRENT_OS = {
    "Darwin": "Mac",
    "Linux": "Linux",
    "Windows": "Windows",
}[platform.system()]


def _load_tool(name: str) -> dict[str, str]:
    with (_SCRIPT_DIR / "diff_reporters.csv").open(newline="") as f:
        for row in csv.DictReader(f):
            if row["name"] == name and row["os"] == CURRENT_OS:
                return row
    assert False, f"Tool {name} not found for OS {CURRENT_OS}"


def _compose_command(tool: dict[str, str], path1: Path, path2: Path) -> list[str]:
    arguments = tool["arguments"]
    if "%s" in arguments:
        replaced = arguments.replace("%s", str(path1), 1).replace("%s", str(path2), 1)
        return [tool["path"], *replaced.split()]
    else:
        return [tool["path"], *arguments.split(), str(path1), str(path2)]


def test_identical_files(tmp_path: Path) -> None:
    reporter = _load_tool("DIFF_COMMAND_LINE")
    file1 = tmp_path / "a.txt"
    file1.write_text(dedent("""\
        XXX
        """))

    file2 = tmp_path / "b.txt"
    file2.write_text(dedent("""\
        XXX
        """))

    result = subprocess.run(_compose_command(reporter, file1, file2), text=True, capture_output=True)
    assert result.returncode == 0


def test_different_files(tmp_path: Path) -> None:
    reporter = _load_tool("DIFF_COMMAND_LINE")
    file1 = tmp_path / "a.txt"
    file1.write_text(dedent("""\
        XXX
        """))

    file2 = tmp_path / "b.txt"
    file2.write_text(dedent("""\
        XXXXXXXXXXXXXX
        """))

    result = subprocess.run(_compose_command(reporter, file1, file2), text=True, capture_output=True)
    assert result.returncode == 1
